name: Generate And Push Postman Collections

on:
  push:
    branches:
      - main
    paths:
      - './**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      
      - name: Install Postman dependencies
        run:  npm i -g openapi-to-postmanv2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Postman Collections
        run: openapi2postmanv2 -s Preview.json  -o Preview_collection.json -p -O folderStrategy=Tags,requestParametersResolution=Schema,responseParametersResolution=Schema,optimizeConversion=false,stackLimit=50
        shell: bash


      - name: Push Postman collections
        run: python ./push_collection_to_repo.py --language python
        shell: bash
